# Generated by Django 3.0.4 on 2020-07-14 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(help_text='Donation ID for the type of donation same as the stripe dashboard', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonationAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='The chosen amount of Donation')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.DonationType')),
            ],
        ),
    ]
