# Generated by Django 3.0.4 on 2020-07-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='description',
            field=models.TextField(default='ABC', help_text='What the donation is for'),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='donation_name',
            field=models.CharField(help_text='Formal Name of the donation', max_length=100, null=True),
        ),
    ]
