# Generated by Django 3.0.4 on 2020-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='date_of_establish',
        ),
        migrations.AddField(
            model_name='college',
            name='year_of_establish',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='website',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
